### ISSUE TITLE
PDTriangleStrain not working?

### ISSUE THREAD

**Issue by dukecyto** [mattoverby/admm-elastic#1]
Hi,

Thanks for making all this public.

I am trying to use your code in a cloth-sim-like scenario, and PDTriangleStrain does not seem to do anything (did not move vertices at all). I switched to LimitedTriangleStrain, and now I am getting the expected result. Could this be a bug?

**Comment by mattoverby** [comment]
Thanks for your interest :). Are you trying to set it through the xml configuration file or manually adding the PDTriangleStrain forces? If it's the former, take a look at the "pdstyle" force in the [windy flag sample](https://github.com/mattoverby/admm-elastic-samples/blob/master/samples/windyflag/cloth.xml). The interface unintuitive, sorry about that. If it's the latter, I'm not sure. I just tested it and the windy flag sample with PDTriangleStrain still works.

**Comment by dukecyto** [comment]
Thanks Matt, and sorry for not being so specific about my current set-up. I wanted to quickly check if this is a known limitation or not. I am manually setting the *TriangleStrain forces in my program (Maya plug-in). For this prototype I am just hard coding the mass to 1.0 for all nodes, stiffness to 1000 for all triangles. The stiffness might be too high compared to your flag example, but the same parameters worked fine for LimitedTriangleStrain. Let me email you a bit more in depth about my project.

**Comment by dukecyto** [comment]
Now I have a better understanding of what limit_min and limit_max does under the hood - I set both of them to 1, and I got the expected result. Thank you for your help!
Please close this issue.
