### ISSUE TITLE
Can you tell me how to run this program

### ISSUE THREAD

**Issue by xianyu12345** [mattoverby/admm-elastic#10]
Can you tell me how to run this program ? thank you

**Comment by mattoverby** [comment]
I've added instructions to the bottom of the readme.

**Comment by xianyu12345** [comment]
I'm sorry to bother you again, I was prompted after running the cmake command:
 Could NOT find MKL (missing: MKL_LIBRARIES MKL_INCLUDE_DIRS MKL_IN
TERFACE_LIBRARY MKL_THREAD_LIBRARY MKL_CORE_LIBRARY) MKL not found, using Eigen solvers
CMake Error at /usr/local/share/cmake-3.12/Modules/FindX11.cmake:429 
(message):
 Could not find X11
Call Stack (most recent call first):
  cmake/FindGLFW.cmake:148 (find_package)
  CMakeLists.txt:68 (find_package)

**Comment by mattoverby** [comment]
Comment out lines 43-51 in CMakeLists which searches for MKL, it's not necessary.
What platform are you compiling on? Assuming linux, you'll need to install libx11-dev.

**Comment by xianyu12345** [comment]
Thank you . I have installed libx11-dev and X11 , but it shows 
CMake Error at cmake/FindGLFW.cmake:151 (message):
  Xrandr library not found - required for GLFW
Call Stack (most recent call first):
  CMakeLists.txt:68 (find_package)
What should I do ?

**Comment by mattoverby** [comment]
You should be able to Google this (and future) cmake errors. There are
several dependencies related to graphics/glfw.
