### ISSUE TITLE
Error in running make -j  ./samples/sca2016/beams

### ISSUE THREAD

**Issue by dragonsan17** [mattoverby/admm-elastic#11]
Hi. I followed the instructions for compiling and running. I generated the build files with cmake and downloaded the dependences into deps folder. When I run the example, as given in the readme, I get the following error.

$ make -j  ./samples/sca2016/beams
g++     samples/sca2016/beams.cpp   -o samples/sca2016/beams
samples/sca2016/beams.cpp:22:10: fatal error: Application.hpp: No such file or directory
   22 | #include "Application.hpp"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: samples/sca2016/beams] Error 1

**Comment by mattoverby** [comment]
I think you skipped some steps

> **cd build**
cmake ..
make -j
./samples/sca2016/beams

And also

> make -j ./samples/sca2016/beams

Should be two commands executed from the build directory

I can reproduce your error if I just call "make -j ./samples/sca2016/beams" from the root directory, which is not the right way to build the code.
