### ISSUE TITLE
last_prox_result is not initialized

### ISSUE THREAD

**Issue by Antialiased** [mattoverby/admm-elastic#6]
In the HyperElasticTet constructor, last_prox_result is resized but the data is not initialized. This causes instant explosions in debug mode (at least on MSVC). Possibly there are more lurking uninitialized variables.

**Comment by Antialiased** [comment]
I also get explosions in opt mode when using this element type...

**Comment by Antialiased** [comment]
These opt mode explosions were fixed by removing these lines in StVKProx::value and NHProx::value:
`	if( x[0]<0.0 || x[1]<0.0 || x[2]<0.0 ){ return std::numeric_limits<double>::infinity(); }
`
When this condition triggers it causes cvsrch in cppoptlib to generate NaNs. I assume with optimizations turned on, floating point accuracy is relaxed somewhere in my program and it starts generating very slightly negative values, which causes this.

**Comment by mattoverby** [comment]
Thanks for reporting the issues, I'll fix this up soon. Besides these problems, are there any issues on MSVC? I have not tried compiling in Windows.

**Comment by mattoverby** [comment]
So the last_prox_result should have been initialized with the resize(3,1.0) call, but just in case I split it into two functions (resize and fill). I also replaced returning infinity with float max, which should be more stable and have the same effect.

**Comment by Antialiased** [comment]
I don't have the code in front of me but I think what was happening with resize(3, 1.0) is that the 1.0 was getting implicitly cast to an int, which was resizing to a matrix of 3 rows and 1 column rather than setting the initial values as intended. The library (and Eigen) generates a ton of warnings which I had to turn off so that might be in there somewhere.

Other than these the simulation is stable on MSVC, although the behaviour is quite poor. I will run the examples when I get some time and see if they are consistent with the paper.

Very cool work by the way!

**Comment by mattoverby** [comment]
Thanks! And if you notice further issues on MSVC, please let me know. I don't really do any programming in windows.
