### ISSUE TITLE
Problem with singletet example

### ISSUE THREAD

**Issue by Catrexis** [mattoverby/admm-elastic#7]
Hi =)
I used a projective dynamics solver for my softbody simulation and wanted to change it to your admm solver. I startet with the singletet example but noticed a problem, when I edited it in the following way:
I scaled the tet by 3:
```
        x[0*3 + 1] = 3;
	x[2*3 + 2] = 3;
	x[3*3 + 0] = 3;
```
and chaged the stiffness to 3. Then I moved the x coordinate to -2 instead of 200 to test the behavior in case of inversion. Last, I changed the timestep to 0.4.
I compared the result with my Projective Dynamics Solver. 
After one Step the Point should move to the right to resolve the inversion, but it moves differently depending on `system.settings.admm_iters`:
If it is an odd number < 30, the Point moves correctly to the right after one step (x = -1.03). But if it is an even number it will move to the left instead (x = -2.19), so the result is more inverted than before. If I do more than one step, both cases converge to the same non-inverted tetrahedron but the path is completely different.
If I use admm_iters == 1, it just explodes after a few steps.
If I use admm_iters > 30, there is still this strange difference between odd and even iteration counts, but there is also a strange y and z direction movement of the point.

This problems are gone, when I change a line of the projection step in Tetforce.cpp:
I changed
`Matrix<double,3,3> F = Map<Matrix<double,3,3> >(DixPlusUi.data());`
to
`Matrix<double,3,3> F = Map<Matrix<double,3,3> >(Dix.data());`
because I noticed, that F differs from the right deformation gradient in the first case.
but in your paper you wrote that one has to use the DixPlusUi, so I think my fix is not the right way.

I'm not very familar with ADMM, so can you tell me, what causes this problem? Do I have to use odd iteration counts? 

Here my singletet.cpp:
```
#include "System.hpp"
#include "AnchorForce.hpp"
#include "TetForce.hpp"
using namespace admm;
bool setup( System *system );


int main(int argc, char *argv[]){

	// Set up our solver (add nodes and forces)
	System system;
	if( !setup( &system ) ){ return 0; }

	// Initialize the solver. This creates the global matrices and
	// verifies input. It will return false on a failure.
	double timestep_s = 0.4; // unreasonably large but this is just a test
	system.settings.timestep_s = timestep_s;
	if( !system.initialize() ){ return 0; }

	// Now move the 4th node's x out and see where it ends up after one step
	system.m_x[3*3] = -2.0;
	
	system.settings.admm_iters = 6;
	for(unsigned int i = 0; i < 200; i++)
	{
		system.step();
		std::cout << i << ": "<< system.m_x[3*3] << std::endl;
	}
	return 0;
}



bool setup( System *system ){

	using namespace Eigen;
	system->settings.verbose = 0; // less prints

	// Add nodes to the system.
	// We can add the necessary values directly:
	if( false ){

		system->m_v.resize(4*3); // node velocities
		system->m_v.fill(0);
		system->m_masses.resize(4*3); // node masses (vector is scaled x3)
		system->m_masses.fill(1);

		Vector3d nodes[4];
		nodes[0] = Vector3d(0,3,0);
		nodes[1] = Vector3d(0,0,0);
		nodes[2] = Vector3d(0,0,3);
		nodes[3] = Vector3d(3,0,0);

		system->m_x.resize(4*3); // node positions
		for( int i=0; i<4; ++i ){
			for( int j=0; j<3; ++j ){ system->m_x[i*3+j] = nodes[i][j]; }
		}
	}

	// Or use the add_nodes function in System:
	else {
		VectorXd x(4*3), m(4*3); // size of node positions/masses is num nodes x3
		m.fill(1); // set node masses to 1
		x.fill(0); // use unit node positions
		x[0*3 + 1] = 3;
		x[2*3 + 2] = 3;
		x[3*3 + 0] = 3;

		// No need to add velocities, they default to zero
		system->add_nodes( x, m );
	}
	
	// Add tet force
	double stiff = 3;
	std::shared_ptr<LinearTetStrain> tf( new LinearTetStrain( 0, 1, 2, 3, stiff ) );
	system->forces.push_back( tf );
	
	// Anchor 3 nodes
	for( int i=0; i<3; ++i ){
		std::shared_ptr<Force> af( new StaticAnchor( i ) );

		// When adding forces to the system, you can just push them on the
		// forces vector in any order.
		system->forces.push_back( af );
	}


	return true;
}
```

**Comment by mattoverby** [comment]
Hi Catrexis, thanks for posting the issue and I'm sorry for the late reply. That is indeed odd behavior as you've described. I have some other things to take care of at the moment, but will look into this soon.

**Comment by mattoverby** [comment]
Problem is fixed in new source.
